# Generated by Django 6.0.2 on 2026-03-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True)),
                ('porte', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('castrado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NO_ABRIGO', 'No Abrigo'), ('ADOTADO', 'Adotado'), ('FALECIDO', 'Falecido'), ('DESAPARECIDO', 'Desaparecido'), ('LT', 'Lar Temporário')], default='NO_ABRIGO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adotante', models.CharField(max_length=150)),
                ('telefone_adotante', models.CharField(blank=True, default='', max_length=30)),
                ('data_adocao', models.DateField()),
                ('responsavel_acompanhamento', models.CharField(blank=True, default='', max_length=150)),
                ('ultimo_acompanhamento', models.DateField(blank=True, null=True)),
                ('castrado_pos_adocao', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='adocao', to='animais.animal')),
            ],
        ),
    ]
