# Generated by Django 6.0.3 on 2026-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aparencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='animal',
            name='comportamento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
