# Generated by Django 6.0.3 on 2026-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuário')], default='USUARIO', max_length=10),
        ),
    ]
