# Generated by Django 6.0.2 on 2026-03-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_banho', models.DateField()),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banhos', to='animais.animal')),
            ],
            options={
                'ordering': ['-data_banho'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VERMIFUGO', 'Vermífugo'), ('CARRAPATICIDA', 'Carrapaticida')], max_length=15)),
                ('produto', models.CharField(blank=True, default='', max_length=150)),
                ('data_aplicacao', models.DateField()),
                ('proxima_data', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='animais.animal')),
            ],
            options={
                'ordering': ['-data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANTIRABICA', 'Antirrábica'), ('V10', 'V8/V10'), ('GRIPE', 'Gripe'), ('OUTRA', 'Outra')], max_length=15)),
                ('dose', models.CharField(blank=True, choices=[('1_DOSE', '1ª Dose'), ('2_DOSE', '2ª Dose'), ('3_DOSE', '3ª Dose'), ('REFORCO', 'Reforço')], max_length=10, null=True)),
                ('data_aplicacao', models.DateField()),
                ('proxima_data', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='animais.animal')),
            ],
            options={
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
