# Generated by Django 6.0.3 on 2026-03-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animal_foto'),
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamento',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='animal',
        ),
        migrations.CreateModel(
            name='RegistroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANTIRABICA', 'Vacina Antirrábica'), ('V10', 'Vacina V10'), ('OUTRA_VACINA', 'Outra Vacina'), ('VERMIFUGO', 'Vermífugo'), ('CARRAPATICIDA', 'Carrapaticida')], max_length=20)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saude', to='animais.animal')),
            ],
            options={
                'ordering': ['-data_aplicacao'],
            },
        ),
        migrations.DeleteModel(
            name='Banho',
        ),
        migrations.DeleteModel(
            name='Tratamento',
        ),
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
