# Generated by Django 6.0.2 on 2026-03-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
        migrations.AddField(
            model_name='conta',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conta',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('VETERINARIO', 'Veterinário'), ('MEDICAMENTO', 'Medicamento'), ('HIGIENE', 'Higiene'), ('INFRAESTRUTURA', 'Infraestrutura'), ('TRANSPORTE', 'Transporte'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conta',
            name='fornecedor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='financeiro.conta'),
        ),
    ]
